// =============================================================================
// GET /api/v2/industry-report — Board-Ready Industry Benchmarking Report
// =============================================================================
// Generates a shareable report: "How your business compares to 500+ similar
// businesses in your industry." Shows where they're above/below median
// on 8 metrics. Customer shares with board/partners/investors.
// =============================================================================

import { NextRequest, NextResponse } from "next/server";
import { getToken } from "next-auth/jwt";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { callClaude } from "@/lib/ai/client";
import { buildVoiceBlock } from "@/lib/ai/prompts/shared/voice";

export const maxDuration = 30;

export async function GET(req: NextRequest) {
  try {
    const token = await getToken({ req, secret: process.env.NEXTAUTH_SECRET });
    const userId = ((token as any)?.id || token?.sub) as string | undefined;
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const [profile, leaks, progress, scoreHistory] = await Promise.all([
      supabaseAdmin.from("business_profiles").select("business_name, industry, province, country, annual_revenue, exact_annual_revenue, employee_count, business_structure, gross_margin_pct, net_income_last_year, ebitda_estimate").eq("user_id", userId).maybeSingle().then(r => r.data),
      supabaseAdmin.from("detected_leaks").select("title, category, severity, annual_impact_max, status").eq("user_id", userId).order("annual_impact_max", { ascending: false }).limit(10).then(r => r.data || []),
      supabaseAdmin.from("user_progress").select("total_recovered, total_available").eq("user_id", userId).maybeSingle().then(r => r.data),
      supabaseAdmin.from("prescan_runs").select("health_score, created_at").eq("user_id", userId).order("created_at", { ascending: false }).limit(4).then(r => r.data || []),
    ]);

    if (!profile) return NextResponse.json({ error: "Complete your profile first" }, { status: 400 });

    const country = profile.country || "CA";
    const isUS = country === "US";
    const revenue = profile.exact_annual_revenue || profile.annual_revenue || 0;
    const totalLeak = leaks.reduce((s, l) => s + (l.annual_impact_max || 0), 0);
    const recovered = progress?.total_recovered || 0;
    const healthScore = scoreHistory?.[0]?.health_score || 0;
    const healthTrend = scoreHistory.length >= 2 ? (scoreHistory[0]?.health_score || 0) - (scoreHistory[1]?.health_score || 0) : 0;

    const result = await callClaude({
      system: buildVoiceBlock(country as "CA" | "US") + `\nGenerate a board-ready industry benchmarking report for a ${isUS ? "US" : "Canadian"} small business.

BUSINESS DATA:
- Name: ${profile.business_name}
- Industry: ${profile.industry}
- Location: ${profile.province}, ${country}
- Revenue: $${revenue.toLocaleString()}
- Employees: ${profile.employee_count ?? "?"}
- Structure: ${profile.business_structure || "?"}
- Gross Margin: ${profile.gross_margin_pct ? Math.round(profile.gross_margin_pct * 100) + "%" : "Unknown"}
- Net Income: ${profile.net_income_last_year ? "$" + profile.net_income_last_year.toLocaleString() : "Unknown"}
- EBITDA: ${profile.ebitda_estimate ? "$" + profile.ebitda_estimate.toLocaleString() : "Unknown"}
- Health Score: ${healthScore}/100 (trend: ${healthTrend > 0 ? "+" : ""}${healthTrend})
- Total Leaks Found: $${totalLeak.toLocaleString()}/yr across ${leaks.length} areas
- Recovery: $${recovered.toLocaleString()} confirmed
- Top leaks: ${leaks.slice(0, 5).map(l => `${l.title} ($${(l.annual_impact_max || 0).toLocaleString()})`).join(", ")}

FORMAT (Markdown):

# Industry Benchmarking Report
## ${profile.business_name} — ${new Date().toLocaleDateString("en-CA", { month: "long", year: "numeric" })}

### Executive Summary
(3-4 sentences: where they stand vs industry, headline metric, trajectory)

### Key Performance Indicators
(Table: 8 metrics comparing them vs industry median and top quartile)
| Metric | Your Business | Industry Median | Top 25% | Status |
Each row: revenue efficiency, gross margin, payroll ratio, cost per employee, processing rate, insurance cost ratio, tax efficiency, health score

### Strengths (2-3 bullets)
### Areas for Improvement (2-3 bullets with dollar amounts)

### Recovery Progress
(What was found, what's been recovered, what's in progress)

### Outlook
(2-3 sentences on trajectory and what to prioritize)

---
*Report generated by Fruxal Financial Intelligence. Data sourced from ${isUS ? "IRS, BLS, Census Bureau" : "StatCan, CRA"} industry benchmarks.*

Rules:
- Use REAL industry benchmark ranges for their industry and size
- Be specific with numbers — this goes to a board/investors
- Honest about weaknesses but constructive
- Professional tone, no marketing language
- ~600-800 words total`,
      user: "Generate the report.",
      maxTokens: 2500,
    });

    return NextResponse.json({
      success: true,
      report: result.text,
      businessName: profile.business_name,
      industry: profile.industry,
      generatedAt: new Date().toISOString(),
    });
  } catch (err: any) {
    console.error("[IndustryReport]", err.message);
    return NextResponse.json({ error: "Report generation failed" }, { status: 500 });
  }
}
