-- ============================================================================
-- 049: CANADA-FIRST EXPANSION
-- ============================================================================
-- 1. Add province column to businesses
-- 2. Canadian government programs → ALL 156 industries
-- 3. Canadian-specific tools → ALL 156 industries
-- 4. Provincial payroll/tax awareness
-- ============================================================================

-- ─── 1. Add province to businesses ───────────────────────────────────────────
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS province TEXT;
COMMENT ON COLUMN businesses.province IS 'Province/state code: ON, QC, BC, AB, etc.';

-- HST/GST/PST rates by province for future use
CREATE TABLE IF NOT EXISTS province_tax_rates (
  province_code TEXT PRIMARY KEY,
  province_name TEXT NOT NULL,
  country TEXT NOT NULL DEFAULT 'CA',
  gst_rate NUMERIC(4,2) DEFAULT 5.0,
  pst_rate NUMERIC(4,2) DEFAULT 0,
  hst_rate NUMERIC(4,2) DEFAULT 0,
  total_sales_tax NUMERIC(4,2) NOT NULL,
  payroll_health_tax_threshold INTEGER DEFAULT 0,
  wsib_name TEXT DEFAULT 'WSIB',
  notes TEXT
);

INSERT INTO province_tax_rates (province_code, province_name, gst_rate, pst_rate, hst_rate, total_sales_tax, payroll_health_tax_threshold, wsib_name, notes)
VALUES
  ('ON', 'Ontario',            0,    0,    13,   13,   490000, 'WSIB',   'HST province. EHT starts at $490K payroll.'),
  ('QC', 'Quebec',             5,    9.975,0,    14.975, 1000000, 'CNESST', 'GST+QST. QPP instead of CPP. QPIP mandatory.'),
  ('BC', 'British Columbia',   5,    7,    0,    12,   500000, 'WorkSafeBC', 'GST+PST. Employer health tax >$500K payroll.'),
  ('AB', 'Alberta',            5,    0,    0,    5,    0,      'WCB Alberta', 'GST only. No provincial sales tax. No payroll health tax.'),
  ('SK', 'Saskatchewan',       5,    6,    0,    11,   0,      'WCB Sask', 'GST+PST.'),
  ('MB', 'Manitoba',           5,    7,    0,    12,   2250000,'WCB Manitoba', 'GST+PST. Health & education levy >$2.25M.'),
  ('NB', 'New Brunswick',      0,    0,    15,   15,   0,      'WorkSafeNB', 'HST province.'),
  ('NS', 'Nova Scotia',        0,    0,    15,   15,   0,      'WCB NS', 'HST province.'),
  ('PE', 'Prince Edward Island',0,   0,    15,   15,   0,      'WCB PEI', 'HST province.'),
  ('NL', 'Newfoundland',       0,    0,    15,   15,   0,      'WorkplaceNL', 'HST province.'),
  ('NT', 'Northwest Territories',5,  0,    0,    5,    0,      'WSCC', 'GST only.'),
  ('YT', 'Yukon',              5,    0,    0,    5,    0,      'YWCHSB', 'GST only.'),
  ('NU', 'Nunavut',            5,    0,    0,    5,    0,      'WSCC', 'GST only.')
ON CONFLICT (province_code) DO NOTHING;


-- ─── 2. Canadian Government Programs → ALL 156 industries ────────────────────
-- These are free money / grants that every Canadian business should know about

-- SR&ED Tax Credits (any business doing innovation/R&D)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'sred-tax-credit', 'SR&ED Tax Credits (CRA)', 'FREE', 'Government',
  'Federal R&D tax credit: 15% non-refundable or 35% refundable for CCPCs. If you improve processes, develop products, or solve technical problems, you likely qualify. Average claim: $50K-$200K.',
  'https://www.canada.ca/en/revenue-agency/services/scientific-research-experimental-development-tax-incentive-program.html',
  ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- CSBFP Loan (equipment, leasehold, technology — up to $1M)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'csbfp-loan', 'CSBFP Loan (Gov-Backed)', 'FREE', 'Government',
  'Canada Small Business Financing Program: government-backed loans up to $1M for equipment, leaseholds, and technology. Just 2% registration fee. Your bank processes it — ask them directly.',
  'https://ised-isde.canada.ca/site/canada-small-business-financing-program',
  ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- CDAP (Canada Digital Adoption Program — $15K grant + $100K BDC loan)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'cdap-grant', 'CDAP Digital Adoption Grant', 'FREE', 'Government',
  'Up to $15,000 grant + $100K interest-free BDC loan to adopt new digital tools. Covers e-commerce, accounting software, CRM, POS systems, and more. Most small businesses qualify.',
  'https://ised-isde.canada.ca/site/canada-digital-adoption-program',
  ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- NRC IRAP (R&D funding up to $10M)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'nrc-irap', 'NRC IRAP Funding', 'FREE', 'Government',
  'Non-repayable funding for SME innovation. Covers salaries, contractors, and materials for R&D projects. Advisory services included. Must be under 500 employees.',
  'https://nrc.canada.ca/en/support-technology-innovation',
  ARRAY['CA']
FROM (VALUES ('app-development'),('cybersecurity'),('data-analytics'),('ecommerce'),('engineering'),('environmental-consulting'),('food-processing'),('healthcare'),('it-services'),('managed-service-provider'),('manufacturing'),('media-production'),('medical-lab'),('metal-fabrication'),('mining'),('oil-gas'),('plastics-rubber'),('saas'),('solar-energy'),('telecom'),('web-development'),('cannabis'),('beverage-manufacturing'),('agriculture')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- BDC Financing
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'bdc-financing', 'BDC Business Loans', 'FREE', 'Government',
  'Business Development Bank of Canada: loans from $25K to $100M+. More flexible than big banks — they exist specifically to fund small businesses. Free online tools and advisory.',
  'https://www.bdc.ca/en',
  ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- Futurpreneur (age 18-39 startup loans + mentorship)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'futurpreneur', 'Futurpreneur (18-39 yrs)', 'FREE', 'Government',
  'Up to $60K in startup financing + 2 years of mentorship for entrepreneurs age 18-39. Paired with BDC for extra $40K. Free business plan support.',
  'https://www.futurpreneur.ca',
  ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- DIY: Claim your HST/GST Input Tax Credits
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'diy-itc-claim', 'DIY: Claim All Your HST/GST Input Tax Credits', 'FREE', 'Government',
  'Every dollar of HST/GST you pay on business expenses can be claimed back. Most businesses miss 10-20% of eligible ITCs. Keep every receipt. File on time to avoid penalties.',
  NULL, ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- DIY: CCA Immediate Expensing (Canadian version of Section 179)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'diy-cca-expensing', 'DIY: CCA Immediate Expensing (Up to $1.5M)', 'FREE', 'Government',
  'CCPCs can immediately expense up to $1.5M in capital purchases per year. Equipment, vehicles, computers, furniture — write it all off in year one instead of depreciating over time.',
  NULL, ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;


-- ─── 3. Canadian-Specific Tools → ALL 156 industries ─────────────────────────

-- Wealthsimple (investing + tax filing for business owners)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'wealthsimple', 'Wealthsimple', 'AFFILIATE', 'Tax PM',
  'Free tax filing (Wealthsimple Tax). TFSA/RRSP investing for business owners. 100% Canadian-built.',
  'https://www.wealthsimple.com/en-ca', ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- Humi (Canadian HR + payroll)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'humi', 'Humi', 'AFFILIATE', 'Payroll',
  'Canadian-built HR, payroll, and benefits. Handles CPP, EI, provincial taxes, ROEs, and T4s. Built specifically for Canadian compliance.',
  'https://www.humi.ca', ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- Plooto (Canadian B2B payments — like Bill.com for Canada)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'plooto', 'Plooto', 'AFFILIATE', 'Payments',
  'Automate accounts payable and receivable. Pay vendors, collect from customers. Integrates with QuickBooks and Xero. Built for Canadian businesses.',
  'https://www.plooto.com', ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- Bench (Canadian bookkeeping service)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'bench', 'Bench Accounting', 'AFFILIATE', 'Bookkeeping',
  'Canadian-built bookkeeping service. Real humans do your books monthly. Tax-ready financials. Integrates with CRA.',
  'https://bench.co', ARRAY['CA','US']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- Knit People (Canadian payroll + HR)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'knit-people', 'Knit People', 'AFFILIATE', 'Payroll',
  'Canadian payroll from $49/mo. Auto-calculates CPP, EI, provincial tax. Generates T4s and ROEs. Direct CRA integration.',
  'https://www.knitpeople.com', ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;

-- PaySimply (pay CRA taxes by credit card)
INSERT INTO industry_solutions (industry_slug, product_slug, product_name, product_type, category, description, url, regions)
SELECT slug, 'paysimply', 'PaySimply', 'AFFILIATE', 'Tax PM',
  'Pay your CRA taxes, HST/GST, payroll remittances, and property taxes by credit card or e-Transfer. Earn credit card points on tax payments.',
  'https://www.paysimply.ca', ARRAY['CA']
FROM (VALUES ('accounting'),('addiction-treatment'),('agency'),('amusement-recreation'),('app-development'),('appliance-repair'),('architecture'),('auto-body'),('auto-detailing'),('auto-parts'),('auto-repair'),('bakery'),('bar-nightclub'),('barber-shop'),('beauty-salon'),('bed-breakfast'),('beverage-manufacturing'),('bookkeeping'),('bookstore'),('bowling-alley'),('cafe-coffee-shop'),('cannabis'),('cannabis-retail'),('car-dealership'),('car-wash'),('catering'),('childcare-home'),('chiropractic'),('church-religious'),('cleaning'),('clothing-boutique'),('collections-agency'),('computer-repair'),('construction'),('consulting'),('convenience-store'),('courier-delivery'),('cybersecurity'),('dance-studio'),('data-analytics'),('daycare'),('demolition'),('dental'),('driving-school'),('dry-cleaning'),('ecommerce'),('electrical'),('engineering'),('environmental-consulting'),('escape-room'),('event-planning'),('farming'),('fast-food-franchise'),('financial-advisor'),('fishing'),('fitness'),('florist'),('food-delivery'),('food-processing'),('food-truck'),('forestry-logging'),('freelancer-gig'),('freight-broker'),('funeral-home'),('furniture-store'),('golf-course'),('graphic-design'),('greenhouse-nursery'),('grocery'),('gym-crossfit'),('hardware-store'),('healthcare'),('home-care'),('home-inspection'),('home-staging'),('hotel-motel'),('hr-consulting'),('hvac'),('import-export'),('influencer-creator'),('insurance-broker'),('interior-design'),('it-services'),('janitorial-commercial'),('jewelry-store'),('landscaping'),('laundromat'),('law-firm'),('liquor-store'),('locksmith'),('managed-service-provider'),('manufacturing'),('marketing-consultant'),('martial-arts'),('massage-therapy'),('media-production'),('medical-lab'),('medical-spa'),('mental-health'),('metal-fabrication'),('mining'),('mortgage-broker'),('moving-company'),('music-school'),('nail-salon'),('nonprofit'),('oil-gas'),('optometry'),('painting'),('pest-control'),('pet-store'),('pharmacy'),('phone-repair'),('photography'),('physiotherapy'),('plastics-rubber'),('plumbing'),('printing'),('private-school'),('property-management'),('publishing'),('ranching'),('real-estate'),('restaurant'),('retail'),('roofing'),('saas'),('security-guard'),('senior-care'),('solar-energy'),('spa'),('sporting-goods'),('staffing-agency'),('subscription-box'),('surveying'),('tattoo-piercing'),('tax-preparation'),('taxi-rideshare'),('telecom'),('textile-apparel'),('tire-shop'),('towing'),('trades'),('training-coaching'),('translation'),('trucking'),('tutoring'),('upholstery'),('vape-smoke-shop'),('veterinary'),('warehousing'),('waste-management'),('web-development'),('wholesale'),('woodworking'),('yoga-studio')) AS t(slug)
ON CONFLICT (industry_slug, product_slug) DO NOTHING;


-- ─── VERIFY ──────────────────────────────────────────────────────────────────
SELECT 'Canadian tools added:' AS note, COUNT(*) FROM industry_solutions WHERE regions @> ARRAY['CA'] AND NOT regions @> ARRAY['GLOBAL'];
SELECT 'Total rows now:' AS note, COUNT(*) FROM industry_solutions;
