export interface LeakExplanation {
  title: string;
  title_fr: string;
  explanation: string;
  explanation_fr: string;
  proof: string;
  proof_fr: string;
  action: string;
  action_fr: string;
  icon: string;
}

export function getLeakExplanation(code: string, metadata: any, amount: number, lang: string): LeakExplanation {
  const m = metadata || {};
  
  const explanations: Record<string, LeakExplanation> = {
    processing_rate_high: {
      title: 'Card Processing Rate',
      title_fr: 'Taux de traitement des cartes',
      explanation: `Your estimated processing rate (${m.assumed_rate_pct || '2.9'}%) is above the industry median (${m.target_rate_pct || '2.3'}%). On $${(m.card_volume ?? 0).toLocaleString()} in annual card transactions, this gap costs you approximately $${amount.toLocaleString()} per year.`,
      explanation_fr: `Votre taux de traitement estimé (${m.assumed_rate_pct || '2.9'}%) est au-dessus de la médiane de l'industrie (${m.target_rate_pct || '2.3'}%). Sur ${(m.card_volume ?? 0).toLocaleString()} $ de transactions annuelles par carte, cet écart vous coûte environ ${amount.toLocaleString()} $ par année.`,
      proof: `Industry benchmark: ${m.target_rate_pct || '2.3'}% · Your estimated rate: ${m.assumed_rate_pct || '2.9'}% · Annual card volume: $${(m.card_volume ?? 0).toLocaleString()}`,
      proof_fr: `Référence de l'industrie : ${m.target_rate_pct || '2.3'}% · Votre taux estimé : ${m.assumed_rate_pct || '2.9'}% · Volume annuel par carte : ${(m.card_volume ?? 0).toLocaleString()} $`,
      action: 'Request a rate review from your processor, or compare quotes from 2-3 competitors. Most businesses save 0.3-0.5% by simply asking.',
      action_fr: 'Demandez une révision de taux à votre fournisseur, ou comparez les soumissions de 2 à 3 compétiteurs. La plupart des entreprises économisent 0,3 à 0,5% simplement en demandant.',
      icon: '💳',
    },
    rent_or_chair_high: {
      title: 'Rent / Occupancy Costs',
      title_fr: 'Loyer / Coûts d\'occupation',
      explanation: `Your rent-to-revenue ratio (${m.actual_ratio_pct || 'estimated'}%) is higher than the industry benchmark (${m.target_ratio_pct || '4-7'}%). Businesses similar to yours in your province typically spend less on occupancy relative to their revenue.`,
      explanation_fr: `Votre ratio loyer/revenus (${m.actual_ratio_pct || 'estimé'}%) est plus élevé que la référence de l'industrie (${m.target_ratio_pct || '4-7'}%). Les entreprises similaires à la vôtre dans votre province dépensent généralement moins en occupation par rapport à leurs revenus.`,
      proof: `Industry target: ${m.target_ratio_pct || '4-7'}% of revenue · Your estimated ratio: ${m.actual_ratio_pct || 'above benchmark'}`,
      proof_fr: `Cible de l'industrie : ${m.target_ratio_pct || '4-7'}% des revenus · Votre ratio estimé : ${m.actual_ratio_pct || 'au-dessus de la référence'}`,
      action: 'Review your lease terms at renewal. Consider renegotiating or exploring comparable spaces in your area.',
      action_fr: 'Révisez les termes de votre bail au renouvellement. Envisagez de renégocier ou d\'explorer des espaces comparables dans votre secteur.',
      icon: '🏢',
    },
    tax_optimization_gap: {
      title: 'Missed Tax Deductions',
      title_fr: 'Déductions fiscales manquées',
      explanation: `Without dedicated accounting software, businesses in your revenue range typically miss 5-10% of eligible deductions. Based on your annual revenue, this could represent up to $${(amount ?? 0).toLocaleString()} in missed tax savings per year.`,
      explanation_fr: `Sans logiciel de comptabilité dédié, les entreprises dans votre tranche de revenus manquent typiquement 5 à 10% des déductions admissibles. Basé sur vos revenus annuels, cela pourrait représenter jusqu'à ${(amount ?? 0).toLocaleString()} $ en économies fiscales manquées par année.`,
      proof: `Estimated miss rate: ${m.miss_rate_pct || '10'}% of eligible deductions · Common missed items: vehicle expenses, home office, professional development, supplies`,
      proof_fr: `Taux de manquement estimé : ${m.miss_rate_pct || '10'}% des déductions admissibles · Items souvent manqués : dépenses véhicule, bureau à domicile, formation, fournitures`,
      action: 'Implement accounting software (QuickBooks, Wave, or FreshBooks) and consider a year-end review with a tax professional.',
      action_fr: 'Adoptez un logiciel de comptabilité (QuickBooks, Wave ou FreshBooks) et envisagez une révision de fin d\'année avec un professionnel en fiscalité.',
      icon: '📋',
    },
    payroll_ratio_high: {
      title: 'Payroll Efficiency',
      title_fr: 'Efficacité de la paie',
      explanation: `Your estimated payroll-to-revenue ratio is above the industry benchmark for businesses your size. This could indicate opportunities in overtime management, employee classification, or workers comp optimization.`,
      explanation_fr: `Votre ratio paie/revenus estimé est au-dessus de la référence de l'industrie pour les entreprises de votre taille. Cela pourrait indiquer des opportunités en gestion du temps supplémentaire, classification des employés ou optimisation CNESST.`,
      proof: `Industry payroll benchmark: ${m.target_ratio_pct || '15-25'}% of revenue · Your estimated ratio: ${m.actual_ratio_pct || 'above benchmark'}`,
      proof_fr: `Référence paie de l'industrie : ${m.target_ratio_pct || '15-25'}% des revenus · Votre ratio estimé : ${m.actual_ratio_pct || 'au-dessus de la référence'}`,
      action: 'Review overtime policies, verify employee vs. contractor classifications, and ensure workers comp rates are optimized for your industry code.',
      action_fr: 'Révisez vos politiques de temps supplémentaire, vérifiez les classifications employé vs. contractuel, et assurez-vous que vos taux CNESST sont optimisés pour votre code d\'industrie.',
      icon: '👥',
    },
    insurance_overpayment: {
      title: 'Insurance Overpayment',
      title_fr: 'Surpaiement d\'assurance',
      explanation: `Businesses that haven't compared insurance rates in 2+ years typically overpay by 15-25%. Based on industry benchmarks for your revenue level, your insurance costs likely exceed the optimal range.`,
      explanation_fr: `Les entreprises qui n'ont pas comparé leurs taux d'assurance depuis plus de 2 ans surpaient typiquement de 15 à 25%. Basé sur les références de l'industrie pour votre niveau de revenus, vos coûts d'assurance dépassent probablement la fourchette optimale.`,
      proof: `Industry insurance benchmark: ${m.target_ratio_pct || '1-2'}% of revenue · Typical overpayment: 15-25% when not regularly reviewed`,
      proof_fr: `Référence assurance de l'industrie : ${m.target_ratio_pct || '1-2'}% des revenus · Surpaiement typique : 15-25% sans révision régulière`,
      action: 'Get 3 competing quotes for your business insurance. Bundle policies where possible and ask about loyalty discounts.',
      action_fr: 'Obtenez 3 soumissions concurrentes pour votre assurance d\'entreprise. Regroupez vos polices quand possible et demandez des rabais fidélité.',
      icon: '🛡️',
    },
    fuel_vehicle_high: {
      title: 'Fuel & Vehicle Costs',
      title_fr: 'Coûts carburant et véhicule',
      explanation: `Your fuel costs relative to revenue are above the industry average for your fleet size. Route optimization and fuel management programs typically reduce costs by 10-20%.`,
      explanation_fr: `Vos coûts de carburant par rapport aux revenus sont au-dessus de la moyenne de l'industrie pour votre taille de flotte. L'optimisation des trajets et les programmes de gestion du carburant réduisent typiquement les coûts de 10 à 20%.`,
      proof: `Industry fuel benchmark: ${m.target_ratio_pct || '15-22'}% of revenue · Your estimated ratio: ${m.actual_ratio_pct || 'above benchmark'}`,
      proof_fr: `Référence carburant de l'industrie : ${m.target_ratio_pct || '15-22'}% des revenus · Votre ratio estimé : ${m.actual_ratio_pct || 'au-dessus de la référence'}`,
      action: 'Consider fuel card programs, route optimization software, and regular vehicle maintenance to improve fuel efficiency.',
      action_fr: 'Envisagez les programmes de cartes carburant, les logiciels d\'optimisation de trajets et l\'entretien régulier des véhicules.',
      icon: '⛽',
    },
    software_bloat: {
      title: 'Software Subscription Costs',
      title_fr: 'Coûts d\'abonnements logiciels',
      explanation: `Businesses at your revenue level commonly accumulate overlapping software subscriptions. Industry data shows the gap between efficient and bloated software spend is approximately $${(amount ?? 0).toLocaleString()} per year at your scale.`,
      explanation_fr: `Les entreprises à votre niveau de revenus accumulent couramment des abonnements logiciels redondants. Les données de l'industrie montrent que l'écart entre une dépense logicielle efficace et excessive est d'environ ${(amount ?? 0).toLocaleString()} $ par année à votre échelle.`,
      proof: `Efficient software spend: 0.5-1% of revenue · Typical bloated spend: 2-3.5% · Common overlaps: multiple POS, booking, invoicing, or CRM tools`,
      proof_fr: `Dépense logicielle efficace : 0,5-1% des revenus · Dépense excessive typique : 2-3,5% · Chevauchements fréquents : multiples outils de POS, réservation, facturation ou CRM`,
      action: 'Audit all active subscriptions. Look for tools that overlap in functionality and consolidate where possible.',
      action_fr: 'Auditez tous vos abonnements actifs. Identifiez les outils dont les fonctionnalités se chevauchent et consolidez quand possible.',
      icon: '💻',
    },
    banking_fees_high: {
      title: 'Business Banking Fees',
      title_fr: 'Frais bancaires d\'entreprise',
      explanation: `Most business accounts carry fees that can be reduced by comparing packages. At your revenue level, the difference between a standard and optimized banking setup is approximately $${(amount ?? 0).toLocaleString()} per year.`,
      explanation_fr: `La plupart des comptes d'entreprise comportent des frais qui peuvent être réduits en comparant les forfaits. À votre niveau de revenus, la différence entre un forfait standard et un forfait optimisé est d'environ ${(amount ?? 0).toLocaleString()} $ par année.`,
      proof: `Efficient banking cost: 0.3% of revenue · Typical unoptimized: 0.7-1% · Includes: monthly fees, transaction fees, wire transfers, overdraft charges`,
      proof_fr: `Coût bancaire efficace : 0,3% des revenus · Non optimisé typique : 0,7-1% · Inclut : frais mensuels, frais de transaction, virements, frais de découvert`,
      action: 'Compare commercial account packages from 2-3 banks. Ask about fee waivers for maintaining minimum balances.',
      action_fr: 'Comparez les forfaits de compte commercial de 2 à 3 banques. Demandez les dispenses de frais pour le maintien de soldes minimums.',
      icon: '🏦',
    },
    inventory_cogs_high: {
      title: 'Cost of Goods Sold',
      title_fr: 'Coût des marchandises vendues',
      explanation: `Your food/goods cost percentage is above the industry benchmark. A ${((m.actual_ratio_pct ?? 0) - (m.target_ratio_pct ?? 0)).toFixed(1)}% reduction could save approximately $${amount.toLocaleString()} per year.`,
      explanation_fr: `Votre pourcentage de coût de marchandises est au-dessus de la référence de l'industrie. Une réduction de ${((m.actual_ratio_pct ?? 0) - (m.target_ratio_pct ?? 0)).toFixed(1)}% pourrait économiser environ ${amount.toLocaleString()} $ par année.`,
      proof: `Industry COGS benchmark: ${m.target_ratio_pct || '20'}% of revenue · Your ratio: ${m.actual_ratio_pct || 'above benchmark'}%`,
      proof_fr: `Référence COGS de l'industrie : ${m.target_ratio_pct || '20'}% des revenus · Votre ratio : ${m.actual_ratio_pct || 'au-dessus de la référence'}%`,
      action: 'Review supplier contracts, reduce waste and spoilage, and consider bulk purchasing or group buying programs.',
      action_fr: 'Révisez vos contrats fournisseurs, réduisez le gaspillage et les pertes, et envisagez les achats en vrac ou les programmes d\'achats groupés.',
      icon: '📦',
    },
    marketing_waste: {
      title: 'Marketing Spend Efficiency',
      title_fr: 'Efficacité des dépenses marketing',
      explanation: `Your marketing spend relative to revenue is above the efficient range for your industry. Without proper tracking, businesses typically waste 30-50% of their advertising budget on underperforming channels.`,
      explanation_fr: `Vos dépenses marketing par rapport aux revenus sont au-dessus de la fourchette efficace pour votre industrie. Sans suivi adéquat, les entreprises gaspillent typiquement 30 à 50% de leur budget publicitaire sur des canaux sous-performants.`,
      proof: `Efficient marketing spend: 1-3% of revenue · Your estimated range: 6%+ · Common waste: untargeted ads, duplicate campaigns, untracked ROI`,
      proof_fr: `Dépense marketing efficace : 1-3% des revenus · Votre fourchette estimée : 6%+ · Gaspillage fréquent : publicités non ciblées, campagnes dupliquées, ROI non suivi`,
      action: 'Track ROI by channel. Cut underperforming campaigns and reinvest in channels with proven conversion rates.',
      action_fr: 'Suivez le ROI par canal. Coupez les campagnes sous-performantes et réinvestissez dans les canaux avec des taux de conversion prouvés.',
      icon: '📢',
    },
    cash_shrinkage: {
      title: 'Cash Handling Losses',
      title_fr: 'Pertes de manipulation d\'argent comptant',
      explanation: `Cash-heavy businesses lose an average of 2-4% of cash revenue to counting errors, miscounts, and shrinkage. With approximately $${(m.cash_volume ?? 0).toLocaleString()} flowing through cash annually, this represents a significant risk.`,
      explanation_fr: `Les entreprises à forte proportion d'argent comptant perdent en moyenne 2 à 4% de leurs revenus en espèces en erreurs de comptage et pertes. Avec environ ${(m.cash_volume ?? 0).toLocaleString()} $ en comptant annuellement, cela représente un risque important.`,
      proof: `Cash volume: $${(m.cash_volume ?? 0).toLocaleString()}/yr · Estimated shrinkage: ${m.shrink_rate_pct || '2-3'}% · Cash share: ${m.cash_share_pct || '40'}% of revenue`,
      proof_fr: `Volume comptant : ${(m.cash_volume ?? 0).toLocaleString()} $/an · Perte estimée : ${m.shrink_rate_pct || '2-3'}% · Part comptant : ${m.cash_share_pct || '40'}% des revenus`,
      action: 'Implement a POS system with cash tracking, end-of-day reconciliation procedures, and consider accepting more card payments.',
      action_fr: 'Implémentez un système POS avec suivi du comptant, des procédures de réconciliation en fin de journée, et envisagez d\'accepter plus de paiements par carte.',
      icon: '💵',
    },
    utilities_overspend: {
      title: 'Utilities Above Benchmark',
      title_fr: 'Services publics au-dessus de la référence',
      explanation: `Your estimated utility costs are above the industry benchmark for businesses your size. Energy audits show most businesses can reduce utility costs by 15-25% with targeted improvements.`,
      explanation_fr: `Vos coûts estimés de services publics sont au-dessus de la référence pour les entreprises de votre taille. Les audits énergétiques montrent que la plupart des entreprises peuvent réduire ces coûts de 15 à 25%.`,
      proof: `Industry benchmark: ${m.target_pct || '1.8'}% of revenue · Your estimated range: ${m.assumed_pct || '2.5-3.5'}% · Common savings: LED lighting, programmable thermostats, rate comparison`,
      proof_fr: `Référence de l'industrie : ${m.target_pct || '1.8'}% des revenus · Votre fourchette estimée : ${m.assumed_pct || '2.5-3.5'}% · Économies courantes : éclairage LED, thermostats programmables, comparaison des tarifs`,
      action: 'Request an energy audit from Hydro-Québec (free for businesses). Compare electricity and gas rates between providers.',
      action_fr: 'Demandez un audit énergétique d\'Hydro-Québec (gratuit pour les entreprises). Comparez les tarifs d\'électricité et de gaz entre les fournisseurs.',
      icon: '⚡',
    },
    revenue_underpricing: {
      title: 'Revenue Erosion from Underpricing',
      title_fr: 'Érosion des revenus par sous-tarification',
      explanation: `With inflation averaging 3-4% annually, businesses that don't adjust prices lose purchasing power every year. At your revenue level, this gap represents approximately $${(amount ?? 0).toLocaleString()} in lost value annually.`,
      explanation_fr: `Avec une inflation moyenne de 3-4% par année, les entreprises qui n'ajustent pas leurs prix perdent du pouvoir d'achat chaque année. À votre niveau de revenus, cet écart représente environ ${(amount ?? 0).toLocaleString()} $ en valeur perdue annuellement.`,
      proof: `Canadian inflation: 3-4%/yr average · Most SMBs raise prices every 2-3 years, not annually · Estimated pricing gap: ${m.inflation_gap_pct || '2.5'}%`,
      proof_fr: `Inflation canadienne : 3-4%/an en moyenne · La plupart des PME augmentent leurs prix aux 2-3 ans · Écart de prix estimé : ${m.inflation_gap_pct || '2.5'}%`,
      action: 'Review your pricing annually. Even a 2-3% increase aligned with inflation preserves your margins without losing customers.',
      action_fr: 'Révisez vos prix annuellement. Même une augmentation de 2-3% alignée sur l\'inflation préserve vos marges sans perdre de clients.',
      icon: '📈',
    },
    receivables_leakage: {
      title: 'Uncollected Invoices',
      title_fr: 'Factures non collectées',
      explanation: `Service businesses typically write off ${m.write_off_rate_pct || '3-5'}% of invoiced revenue. Without automated follow-up, late and uncollected payments accumulate over the year.`,
      explanation_fr: `Les entreprises de services radient typiquement ${m.write_off_rate_pct || '3-5'}% des revenus facturés. Sans suivi automatisé, les paiements en retard et non collectés s'accumulent au fil de l'année.`,
      proof: `Estimated invoiced revenue: ${m.invoiced_share_pct || '70'}% of total · Write-off rate: ${m.write_off_rate_pct || '5'}% · Industry average collection period: 45-60 days`,
      proof_fr: `Revenus facturés estimés : ${m.invoiced_share_pct || '70'}% du total · Taux de radiation : ${m.write_off_rate_pct || '5'}% · Période de collecte moyenne : 45-60 jours`,
      action: 'Implement automated invoice reminders, require deposits for large projects, and consider offering early payment discounts.',
      action_fr: 'Implémentez des rappels automatiques de factures, exigez des dépôts pour les gros projets, et offrez des rabais pour paiement rapide.',
      icon: '📄',
    },
    late_payment_penalties: {
      title: 'Late Payment Penalties',
      title_fr: 'Pénalités de retard de paiement',
      explanation: `Without a tracking system, businesses average $500-2,000 per year in avoidable late fees on supplier invoices, tax remittances, and utility payments.`,
      explanation_fr: `Sans système de suivi, les entreprises paient en moyenne 500 à 2 000 $ par année en frais de retard évitables sur les factures fournisseurs, remises de taxes et services publics.`,
      proof: `No accounting software detected · Estimated penalty rate: ${m.late_rate_pct || '0.5'}% of revenue · Common penalties: supplier 2% late charge, CRA interest, Hydro penalties`,
      proof_fr: `Aucun logiciel de comptabilité détecté · Taux de pénalité estimé : ${m.late_rate_pct || '0.5'}% des revenus · Pénalités courantes : frais fournisseur 2%, intérêts ARC, pénalités Hydro`,
      action: 'Set up automatic payment reminders or auto-pay for recurring bills. Accounting software like Wave (free) tracks due dates automatically.',
      action_fr: 'Configurez des rappels automatiques ou le paiement automatique pour les factures récurrentes. Un logiciel comme Wave (gratuit) suit les échéances automatiquement.',
      icon: '⏰',
    },
    equipment_depreciation_gap: {
      title: 'Unclaimed Equipment Depreciation',
      title_fr: 'Amortissement d\'équipement non réclamé',
      explanation: `Businesses without accounting software often miss CCA (Capital Cost Allowance) deductions on equipment, vehicle, and technology purchases. This is a direct tax credit you're leaving on the table.`,
      explanation_fr: `Les entreprises sans logiciel de comptabilité manquent souvent les déductions DPA (Déduction pour amortissement) sur les achats d'équipement, véhicules et technologies. C'est un crédit d'impôt direct que vous laissez sur la table.`,
      proof: `No accounting software detected · CCA gap estimate: ${m.cca_gap_pct || '1.5'}% of revenue · Common missed items: tools, computers, vehicles, machinery`,
      proof_fr: `Aucun logiciel de comptabilité détecté · Écart DPA estimé : ${m.cca_gap_pct || '1.5'}% des revenus · Items souvent manqués : outils, ordinateurs, véhicules, machinerie`,
      action: 'Keep a detailed asset register. Claim CCA on all business assets — even small purchases add up over time.',
      action_fr: 'Tenez un registre détaillé de vos actifs. Réclamez la DPA sur tous vos actifs d\'entreprise — même les petits achats s\'accumulent.',
      icon: '🔧',
    },
    employee_turnover_cost: {
      title: 'Employee Turnover Cost',
      title_fr: 'Coûts de roulement du personnel',
      explanation: `With ${m.employee_count || 'several'} employees, the hidden cost of turnover is significant. Each replacement costs 30-50% of that employee's salary in recruiting, training, and lost productivity.`,
      explanation_fr: `Avec ${m.employee_count || 'plusieurs'} employés, le coût caché du roulement est important. Chaque remplacement coûte 30-50% du salaire de l'employé en recrutement, formation et productivité perdue.`,
      proof: `Employee count: ${m.employee_count || 'N/A'} · Canadian SMB turnover: ~${m.turnover_rate_pct || '20'}%/yr · Replacement cost: ~${m.replacement_cost_pct || '35'}% of salary`,
      proof_fr: `Nombre d'employés : ${m.employee_count || 'N/A'} · Roulement PME canadien : ~${m.turnover_rate_pct || '20'}%/an · Coût de remplacement : ~${m.replacement_cost_pct || '35'}% du salaire`,
      action: 'Invest in retention: competitive wages, clear advancement paths, and regular check-ins. Even a 5% reduction in turnover saves thousands.',
      action_fr: 'Investissez dans la rétention : salaires compétitifs, parcours d\'avancement clairs et suivis réguliers. Même une réduction de 5% du roulement économise des milliers.',
      icon: '👥',
    },
    supplier_discount_missed: {
      title: 'Missed Supplier Discounts',
      title_fr: 'Rabais fournisseurs manqués',
      explanation: `Most suppliers offer 2-5% early payment discounts (e.g., "2/10 net 30") that go unclaimed. Based on your estimated purchasing volume, these missed discounts add up to approximately $${(amount ?? 0).toLocaleString()} per year.`,
      explanation_fr: `La plupart des fournisseurs offrent des rabais de 2-5% pour paiement rapide (ex: "2/10 net 30") qui ne sont pas réclamés. Basé sur votre volume d'achat estimé, ces rabais manqués totalisent environ ${(amount ?? 0).toLocaleString()} $ par année.`,
      proof: `Estimated COGS: ${m.cogs_ratio_pct || '20-35'}% of revenue · Available discount: ${m.discount_pct || '2'}% · Most terms: pay within 10 days for discount`,
      proof_fr: `Coût des marchandises estimé : ${m.cogs_ratio_pct || '20-35'}% des revenus · Rabais disponible : ${m.discount_pct || '2'}% · Condition typique : payer dans les 10 jours`,
      action: 'Ask suppliers about early payment discounts. Set up payment schedules to capture them. Negotiate volume pricing annually.',
      action_fr: 'Demandez à vos fournisseurs les rabais pour paiement rapide. Établissez des calendriers de paiement pour les capturer. Négociez les prix de volume annuellement.',
      icon: '🤝',
    },
    debt_interest_high: {
      title: 'Business Debt Interest Gap',
      title_fr: 'Écart d\'intérêt sur la dette d\'entreprise',
      explanation: `Most SMBs carry business debt averaging 15-25% of annual revenue. Interest rates vary by 2-3% between lenders — at your estimated debt level of $${(m.estimated_debt ?? 0).toLocaleString()}, that gap costs approximately $${amount.toLocaleString()} per year.`,
      explanation_fr: `La plupart des PME ont une dette d'entreprise moyenne de 15-25% des revenus annuels. Les taux d'intérêt varient de 2-3% entre prêteurs — avec votre dette estimée de ${(m.estimated_debt ?? 0).toLocaleString()} $, cet écart coûte environ ${amount.toLocaleString()} $ par année.`,
      proof: `Estimated business debt: $${(m.estimated_debt ?? 0).toLocaleString()} · Rate gap: ${m.rate_gap_pct || '2.5'}% · Debt ratio: ~${m.debt_ratio_pct || '20'}% of revenue`,
      proof_fr: `Dette d'entreprise estimée : ${(m.estimated_debt ?? 0).toLocaleString()} $ · Écart de taux : ${m.rate_gap_pct || '2.5'}% · Ratio d'endettement : ~${m.debt_ratio_pct || '20'}% des revenus`,
      action: 'Compare rates from at least 3 lenders. Consider consolidating multiple debts and ask about BDC or Desjardins SMB programs.',
      action_fr: 'Comparez les taux d\'au moins 3 prêteurs. Envisagez de consolider vos dettes et renseignez-vous sur les programmes PME de la BDC ou Desjardins.',
      icon: '💰',
    },
    tax_filing_inefficiency: {
      title: 'GST/HST Input Credits Missed',
      title_fr: 'Crédits de taxe sur intrants manqués',
      explanation: `Without proper tracking, businesses miss 1-2% of eligible GST/HST input tax credits each year. These are taxes you already paid on business expenses that should be credited back to you.`,
      explanation_fr: `Sans suivi adéquat, les entreprises manquent 1-2% des crédits de taxe sur intrants TPS/TVH admissibles chaque année. Ce sont des taxes que vous avez déjà payées sur vos dépenses d'entreprise qui devraient vous être remboursées.`,
      proof: `No accounting software detected · Estimated ITC loss: ${m.itc_loss_rate_pct || '1.5'}% of revenue · Common missed: business meals, office supplies, mileage, home office`,
      proof_fr: `Aucun logiciel de comptabilité détecté · Perte CTI estimée : ${m.itc_loss_rate_pct || '1.5'}% des revenus · Souvent manqués : repas d'affaires, fournitures, kilométrage, bureau à domicile`,
      action: 'Keep all business receipts. Use an app like Dext or QuickBooks receipt capture. File quarterly to recover ITCs faster.',
      action_fr: 'Conservez tous vos reçus d\'affaires. Utilisez une application comme Dext ou QuickBooks. Produisez trimestriellement pour récupérer les CTI plus vite.',
      icon: '🧾',
    },
    professional_fees_high: {
      title: 'Professional Fees Above Optimal',
      title_fr: 'Honoraires professionnels au-dessus de l\'optimal',
      explanation: `Most business owners don't regularly compare accountant, bookkeeper, or lawyer fees. Shopping around typically saves 15-30% without sacrificing quality.`,
      explanation_fr: `La plupart des propriétaires ne comparent pas régulièrement les honoraires de comptable, teneur de livres ou avocat. Magasiner économise typiquement 15-30% sans sacrifier la qualité.`,
      proof: `Estimated overpayment: ${m.overpay_pct || '0.5'}% of revenue · Common issue: paying hourly when flat-fee would be cheaper · Most don't request competing quotes`,
      proof_fr: `Surpaiement estimé : ${m.overpay_pct || '0.5'}% des revenus · Problème courant : payer à l'heure quand un forfait serait moins cher · La plupart ne demandent pas de soumissions concurrentes`,
      action: 'Get quotes from 2-3 accountants or bookkeepers. Ask about flat-rate packages instead of hourly billing.',
      action_fr: 'Obtenez des soumissions de 2-3 comptables ou teneurs de livres. Demandez des forfaits à prix fixe au lieu de la facturation horaire.',
      icon: '📑',
    },
    no_bookkeeping_system: {
      title: 'No Bookkeeping System',
      title_fr: 'Absence de système de comptabilité',
      explanation: `Without a bookkeeping system, money is lost to untracked expenses, lost receipts, duplicate payments, and missed deductions. This is a compound leak that affects multiple areas of your business.`,
      explanation_fr: `Sans système de comptabilité, de l'argent se perd en dépenses non suivies, reçus perdus, paiements en double et déductions manquées. C'est une fuite composée qui affecte plusieurs aspects de votre entreprise.`,
      proof: `No accounting software detected · Estimated compound loss: ${m.gap_rate_pct || '2'}% of revenue · Affects: tax deductions, expense tracking, cash flow visibility`,
      proof_fr: `Aucun logiciel de comptabilité détecté · Perte composée estimée : ${m.gap_rate_pct || '2'}% des revenus · Affecte : déductions fiscales, suivi des dépenses, visibilité des flux de trésorerie`,
      action: 'Start with a free tool like Wave or QuickBooks Simple Start. Even basic tracking eliminates most of these losses.',
      action_fr: 'Commencez avec un outil gratuit comme Wave ou QuickBooks Simple Start. Même un suivi de base élimine la majorité de ces pertes.',
      icon: '📚',
    },
    subcontractor_markup: {
      title: 'Subcontractor Cost Gap',
      title_fr: 'Écart de coûts de sous-traitance',
      explanation: `Subcontractor rates vary widely in your industry. Without competitive bidding and regular rate reviews, businesses typically overpay by 3-5% on subcontracted work.`,
      explanation_fr: `Les taux de sous-traitance varient considérablement dans votre industrie. Sans appels d'offres compétitifs et révisions régulières, les entreprises surpaient typiquement de 3-5%.`,
      proof: `Industry benchmark spread: ${m.bench_p25_pct || '15'}% to ${m.bench_p75_pct || '25'}% of revenue · Optimization gap: ~${m.delta_pct || '4'}%`,
      proof_fr: `Fourchette de l'industrie : ${m.bench_p25_pct || '15'}% à ${m.bench_p75_pct || '25'}% des revenus · Écart d'optimisation : ~${m.delta_pct || '4'}%`,
      action: 'Get 3 quotes for each major subcontract. Build relationships with 2-3 reliable subs and review rates annually.',
      action_fr: 'Obtenez 3 soumissions pour chaque contrat majeur. Développez des relations avec 2-3 sous-traitants fiables et révisez les taux annuellement.',
      icon: '🏗️',
    },
    scheduling_inefficiency: {
      title: 'Scheduling & Overtime Waste',
      title_fr: 'Gaspillage en horaires et temps supplémentaire',
      explanation: `With ${m.employee_count || 'several'} employees, poor scheduling leads to overtime premiums, understaffing during peaks, and overstaffing during slow periods. This typically costs 1-2% of revenue.`,
      explanation_fr: `Avec ${m.employee_count || 'plusieurs'} employés, un mauvais horaire mène à des primes de temps supplémentaire, du sous-effectif en pointe et du sur-effectif en période creuse. Cela coûte typiquement 1-2% des revenus.`,
      proof: `Employee count: ${m.employee_count || 'N/A'} · Estimated scheduling waste: ${m.sched_rate_pct || '1.2'}% of revenue · Common issues: unplanned overtime, shift gaps, manual scheduling`,
      proof_fr: `Nombre d'employés : ${m.employee_count || 'N/A'} · Gaspillage d'horaire estimé : ${m.sched_rate_pct || '1.2'}% des revenus · Problèmes courants : temps supplémentaire non planifié, trous d'horaire, planification manuelle`,
      action: 'Use scheduling software (Deputy, When I Work, or Homebase). Track overtime trends and adjust staffing to demand patterns.',
      action_fr: 'Utilisez un logiciel d\'horaires (Deputy, When I Work ou Homebase). Suivez les tendances de temps supplémentaire et ajustez le personnel aux patterns de demande.',
      icon: '📅',
    },
    no_emergency_fund: {
      title: 'Reactive Cost Premium',
      title_fr: 'Prime de coûts réactifs',
      explanation: `Without cash reserves, businesses pay premium rates for emergency repairs, rush supplier orders, and short-term credit. This reactive approach costs approximately $${(amount ?? 0).toLocaleString()} more per year than proactive management.`,
      explanation_fr: `Sans réserves de trésorerie, les entreprises paient des tarifs premium pour les réparations d'urgence, les commandes urgentes et le crédit à court terme. Cette approche réactive coûte environ ${(amount ?? 0).toLocaleString()} $ de plus par année qu'une gestion proactive.`,
      proof: `Estimated reactive premium: ${m.reactive_rate_pct || '1'}% of revenue · Emergency markup: 25-50% above normal rates · Short-term credit: 18-24% APR vs. planned LOC at 7-10%`,
      proof_fr: `Prime réactive estimée : ${m.reactive_rate_pct || '1'}% des revenus · Majoration d'urgence : 25-50% au-dessus des taux normaux · Crédit à court terme : 18-24% TAP vs. marge planifiée à 7-10%`,
      action: 'Build a 3-month expense reserve gradually. Set up a business line of credit before you need it — rates are better when you\'re not desperate.',
      action_fr: 'Constituez graduellement une réserve de 3 mois de dépenses. Établissez une marge de crédit d\'entreprise avant d\'en avoir besoin — les taux sont meilleurs quand vous n\'êtes pas dans l\'urgence.',
      icon: '🚨',
    },
  };
  
  return explanations[code] || {
    title: code.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
    title_fr: code.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
    explanation: `This area of your business shows potential for optimization based on industry benchmarks.`,
    explanation_fr: `Ce domaine de votre entreprise montre un potentiel d'optimisation basé sur les références de l'industrie.`,
    proof: 'Based on industry benchmark comparison',
    proof_fr: 'Basé sur la comparaison des références de l\'industrie',
    action: 'Connect your financial data for a detailed analysis and specific recommendations.',
    action_fr: 'Connectez vos données financières pour une analyse détaillée et des recommandations spécifiques.',
    icon: '📊',
  };
}
