-- =============================================================================
-- migration_107_contingency_execution.sql
-- All tables added during the contingency model build.
-- Safe to run multiple times (IF NOT EXISTS everywhere).
-- =============================================================================

-- Accountants (internal team members who execute recovery)
CREATE TABLE IF NOT EXISTS accountants (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  email       TEXT NOT NULL UNIQUE,
  province    TEXT,
  specialties JSONB DEFAULT '[]',
  status      TEXT DEFAULT 'active',
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);

-- Execution playbooks (one per finding, generated by Claude after diagnostic)
CREATE TABLE IF NOT EXISTS execution_playbooks (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  diagnostic_report_id  UUID,
  business_id           UUID,
  pipeline_id           UUID,
  finding_id            TEXT,
  finding_title         TEXT,
  category              TEXT,
  severity              TEXT DEFAULT 'medium',
  amount_recoverable    NUMERIC DEFAULT 0,
  status                TEXT DEFAULT 'queued',  -- queued | in_progress | submitted | confirmed | closed
  assigned_to           UUID REFERENCES accountants(id),
  execution_steps       JSONB DEFAULT '[]',
  documents_needed      JSONB DEFAULT '[]',
  draft_template        TEXT DEFAULT '',
  cra_forms             JSONB DEFAULT '[]',
  who_executes          TEXT DEFAULT 'accountant',
  estimated_hours       NUMERIC,
  quick_win             BOOLEAN DEFAULT false,
  notes                 TEXT,
  confirmed_amount      NUMERIC,
  confirmed_at          TIMESTAMPTZ,
  created_at            TIMESTAMPTZ DEFAULT now(),
  updated_at            TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_execution_playbooks_report    ON execution_playbooks(diagnostic_report_id);
CREATE INDEX IF NOT EXISTS idx_execution_playbooks_business  ON execution_playbooks(business_id);
CREATE INDEX IF NOT EXISTS idx_execution_playbooks_pipeline  ON execution_playbooks(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_execution_playbooks_assigned  ON execution_playbooks(assigned_to);
CREATE INDEX IF NOT EXISTS idx_execution_playbooks_status    ON execution_playbooks(status);

-- Fruxal fee invoices
CREATE TABLE IF NOT EXISTS fruxal_invoices (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pipeline_id       UUID UNIQUE,
  invoice_number    TEXT,
  company_name      TEXT,
  contact_email     TEXT,
  confirmed_savings NUMERIC DEFAULT 0,
  fee_percentage    NUMERIC DEFAULT 12,
  fee_amount        NUMERIC DEFAULT 0,
  payment_url       TEXT,
  status            TEXT DEFAULT 'pending',  -- pending | sent | paid | overdue
  notes             TEXT,
  sent_at           TIMESTAMPTZ,
  paid_at           TIMESTAMPTZ,
  created_at        TIMESTAMPTZ DEFAULT now(),
  updated_at        TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_fruxal_invoices_pipeline ON fruxal_invoices(pipeline_id);
CREATE INDEX IF NOT EXISTS idx_fruxal_invoices_status   ON fruxal_invoices(status);

-- Post-call debriefs (rep fills after each call)
CREATE TABLE IF NOT EXISTS call_debriefs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pipeline_id     UUID,
  rep_id          TEXT,
  call_outcome    TEXT,    -- ready_to_sign | needs_time | not_interested
  agreed_findings JSONB DEFAULT '[]',
  client_concerns TEXT,
  next_action     TEXT,
  notes           TEXT,
  total_agreed    NUMERIC DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_call_debriefs_pipeline ON call_debriefs(pipeline_id);

-- Pipeline additions (confirmed savings + agreement token + signature)
ALTER TABLE tier3_pipeline
  ADD COLUMN IF NOT EXISTS confirmed_savings       NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS agreed_findings         JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS agreement_token         TEXT,
  ADD COLUMN IF NOT EXISTS agreement_token_expiry  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS signed_at               TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS signatory_name          TEXT,
  ADD COLUMN IF NOT EXISTS signatory_title         TEXT;

-- Tier3 agreements: add pipeline_id for the new signing flow
ALTER TABLE tier3_agreements
  ADD COLUMN IF NOT EXISTS pipeline_id      UUID,
  ADD COLUMN IF NOT EXISTS signatory_name   TEXT,
  ADD COLUMN IF NOT EXISTS signatory_title  TEXT,
  ADD COLUMN IF NOT EXISTS ip_address       TEXT;

-- Rep commissions: add pipeline_id
ALTER TABLE tier3_rep_commissions
  ADD COLUMN IF NOT EXISTS pipeline_id UUID;

-- Indexes for new pipeline columns
CREATE INDEX IF NOT EXISTS idx_pipeline_agreement_token ON tier3_pipeline(agreement_token) WHERE agreement_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pipeline_stage_user      ON tier3_pipeline(user_id, stage);
